language: node_js
node_js:
  - "node"
  - "lts/*"
  - "12"
  - "10"
install:
  - npm install -g codecov
  - npm install
script:
  - npm run lint
  - npm run flow check
  - npm test
after_success:
  - codecov
