language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
sudo: false
install:
  - npm install -g codecov
  - npm install
script:
  - npm run lint
  - npm run flow
  - npm test
after_success:
  - codecov
