language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
sudo: false
install:
  - npm install -g codecov
  - npm install
script:
  - npm run lint
  - npm run flow check
  - npm test
after_success:
  - codecov
